import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { motion } from "framer-motion";
import { Brain, Sparkles, Map, BookOpen, Flame, ChevronRight, Zap, Target } from "lucide-react";

const features = [
  { icon: Sparkles, title: "AI Roadmap", desc: "Personalized 12-week prep plan generated by AI based on your profile" },
  { icon: BookOpen, title: "Question Bank", desc: "DSA, aptitude, core CS, and HR questions with timer and tracking" },
  { icon: Map, title: "Smart Resources", desc: "Curated YouTube videos, docs, and practice platforms for each topic" },
  { icon: Flame, title: "Streaks & XP", desc: "Gamified daily streaks, XP points, levels, and achievement badges" },
];

const Index = () => {
  return (
    <div className="min-h-screen">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 py-4 max-w-6xl mx-auto">
        <div className="flex items-center gap-2">
          <Brain className="h-7 w-7 text-primary" />
          <span className="text-xl font-bold">PrepGenius</span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login">
            <Button variant="ghost" size="sm">Sign In</Button>
          </Link>
          <Link to="/register">
            <Button size="sm" className="gradient-primary text-primary-foreground">Get Started</Button>
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-6xl mx-auto px-6 pt-20 pb-24 text-center">
        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
          <Badge className="gradient-accent text-accent-foreground mb-6 px-4 py-1.5 text-sm">
            <Zap className="h-3.5 w-3.5 mr-1" /> AI-Powered Placement Prep
          </Badge>
          <h1 className="text-5xl md:text-7xl font-bold leading-tight mb-6">
            Your personalized<br />
            <span className="bg-clip-text text-transparent" style={{ backgroundImage: "var(--gradient-primary)" }}>
              placement roadmap
            </span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
            PrepGenius uses AI to build a custom prep plan based on your skills, goals, and timeline. Track progress, solve questions, and level up.
          </p>
          <div className="flex items-center justify-center gap-4">
            <Link to="/register">
              <Button size="lg" className="gradient-primary text-primary-foreground shadow-glow-primary text-base px-8">
                Start Free <ChevronRight className="h-4 w-4 ml-1" />
              </Button>
            </Link>
            <Link to="/login">
              <Button size="lg" variant="outline" className="text-base px-8">
                Sign In
              </Button>
            </Link>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section className="max-w-6xl mx-auto px-6 pb-24">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + i * 0.1 }}
              className="glass rounded-xl p-6 hover:border-primary/30 transition-all"
            >
              <div className="inline-flex p-3 rounded-lg bg-primary/10 mb-4">
                <f.icon className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-lg font-semibold mb-2">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="max-w-6xl mx-auto px-6 pb-24 text-center">
        <div className="glass rounded-2xl p-12">
          <Target className="h-12 w-12 text-accent mx-auto mb-4" />
          <h2 className="text-3xl font-bold mb-3">Ready to ace your placements?</h2>
          <p className="text-muted-foreground mb-6">Join thousands of students preparing smarter with AI</p>
          <Link to="/register">
            <Button size="lg" className="gradient-primary text-primary-foreground shadow-glow-primary">
              Get Started for Free
            </Button>
          </Link>
        </div>
      </section>
    </div>
  );
};

export default Index;
