import { apiGet, apiPost } from "./services/api.js"

const statusEl = document.getElementById("career-status")
const outputEl = document.getElementById("career-output")
const buttonEl = document.getElementById("recommend-career-btn")

function setStatus(text, isError = false){
  statusEl.textContent = text
  statusEl.className = isError ? "status error" : "status success"
}

function setBusy(busy){
  buttonEl.disabled = busy
  buttonEl.textContent = busy ? "Analyzing..." : buttonEl.dataset.label
}

function listMarkup(items, emptyText){
  const safe = Array.isArray(items) ? items : []
  if(safe.length === 0){
    return `<p class="meta">${emptyText}</p>`
  }
  return `
    <ul class="result-list">
      ${safe.map(item => `<li>${item}</li>`).join("")}
    </ul>
  `
}

function renderRecommendation(recommendation, source = "ai"){
  if(!recommendation){
    outputEl.innerHTML = `<p class="section-subtitle">No recommendation yet.</p>`
    return
  }

  const sourceText = source === "fallback"
    ? "Generated from fallback career scoring."
    : `Generated by AI model (${source || "provider"}).`

  const topRoles = Array.isArray(recommendation.matches)
    ? recommendation.matches.map((item, index) => `${index + 1}. ${item.role} (${item.score}) - ${item.reason}`)
    : []

  const pathCards = Array.isArray(recommendation.recommendedPaths)
    ? recommendation.recommendedPaths
    : []

  outputEl.innerHTML = `
    <p class="eyebrow">Career Recommendation</p>
    <h2>Your Best-Fit Roles</h2>
    <p class="section-subtitle">${recommendation.summary || ""}</p>
    <p class="meta">${sourceText}</p>

    <h3>Top Career Matches</h3>
    ${listMarkup(topRoles, "No career matches available.")}

    <h3>Recommended Learning Paths</h3>
    ${pathCards.length === 0
      ? '<p class="meta">No path recommendations available yet.</p>'
      : `<div class="roadmap-grid">
        ${pathCards.map(path => `
          <article class="roadmap-phase">
            <h3>${path.title}</h3>
            <p class="meta">Path ID: ${path.id}</p>
            <p class="meta">${path.reason || "Recommended based on your top matches."}</p>
          </article>
        `).join("")}
      </div>`
    }

    <div class="actions">
      <a href="dashboard.html"><button type="button">Continue to Dashboard</button></a>
    </div>
  `
}

function getAnswers(){
  return {
    logicPreference: document.getElementById("logic-preference").value,
    uiPreference: document.getElementById("ui-preference").value,
    mathPreference: document.getElementById("math-preference").value,
    infraPreference: document.getElementById("infra-preference").value,
    collaborationPreference: document.getElementById("collab-preference").value
  }
}

async function loadLatest(){
  try{
    const data = await apiGet("/ai/career-recommend/latest")
    renderRecommendation(data.recommendation, "ai")
  }catch(_error){
    renderRecommendation(null)
  }
}

async function runRecommendation(){
  const answers = getAnswers()
  try{
    setBusy(true)
    setStatus("")
    const data = await apiPost("/ai/career-recommend", answers)
    renderRecommendation(data.recommendation, data.source)
    setStatus("Career recommendation generated.")
  }catch(error){
    setStatus(error.message, true)
  }finally{
    setBusy(false)
  }
}

buttonEl.addEventListener("click", runRecommendation)
loadLatest()
