import { apiGet, apiPost } from "./services/api.js"
import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.min.mjs"

const statusEl = document.getElementById("skill-gap-status")
const outputEl = document.getElementById("skill-gap-output")
const analyzeBtn = document.getElementById("analyze-skill-gap-btn")
const resumePdfInput = document.getElementById("resume-pdf")
const resumeTextEl = document.getElementById("resume-text")

pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.min.mjs"

function setStatus(text, isError = false){
  statusEl.textContent = text
  statusEl.className = isError ? "status error" : "status success"
}

function setBusy(busy){
  analyzeBtn.disabled = busy
  analyzeBtn.textContent = busy ? "Analyzing..." : analyzeBtn.dataset.label
}

function listMarkup(items, emptyText){
  const safe = Array.isArray(items) ? items : []
  if(safe.length === 0){
    return `<p class="meta">${emptyText}</p>`
  }
  return `
    <ul class="result-list">
      ${safe.map(item => `<li>${item}</li>`).join("")}
    </ul>
  `
}

function pathsMarkup(paths){
  const safe = Array.isArray(paths) ? paths : []
  if(safe.length === 0){
    return `<p class="meta">No matching path recommendation yet.</p>`
  }
  return `
    <div class="roadmap-grid">
      ${safe.map(path => `
        <article class="roadmap-phase">
          <h3>${path.title}</h3>
          <p class="meta">Path ID: ${path.id}</p>
          <p class="meta">${path.reason || "Recommended based on skill gaps"}</p>
        </article>
      `).join("")}
    </div>
  `
}

function fallbackPathsForRole(targetRole){
  const role = `${targetRole || ""}`.toLowerCase()
  if(role.includes("frontend") || role.includes("ui")){
    return [
      { id: "frontend", title: "Frontend Developer", reason: "Best fit for UI-focused growth." },
      { id: "backend", title: "Backend Developer", reason: "Complements frontend with API skills." }
    ]
  }
  if(role.includes("devops") || role.includes("sre") || role.includes("platform")){
    return [
      { id: "devops", title: "DevOps Engineer", reason: "Directly aligned with your role target." },
      { id: "cloud", title: "Cloud Engineer", reason: "Supports infra and deployment expertise." }
    ]
  }
  if(role.includes("cloud") || role.includes("aws") || role.includes("gcp") || role.includes("azure")){
    return [
      { id: "cloud", title: "Cloud Engineer", reason: "Primary path for cloud fundamentals." },
      { id: "devops", title: "DevOps Engineer", reason: "Strengthens automation and operations." }
    ]
  }
  return [
    { id: "backend", title: "Backend Developer", reason: "Strong systems foundation for many roles." },
    { id: "cloud", title: "Cloud Engineer", reason: "Improves deployment and scalability skills." }
  ]
}

function renderReport(report, source = "ai"){
  if(!report){
    outputEl.innerHTML = `<p class="section-subtitle">No report yet.</p>`
    return
  }

  const sourceText = source === "fallback"
    ? "Generated from fallback analyzer (AI unavailable)."
    : `Generated by AI model (${source || "provider"}).`
  outputEl.innerHTML = `
    <p class="eyebrow">Skill Gap Report</p>
    <h2>${report.targetRole} Readiness Analysis</h2>
    <p class="section-subtitle">${report.summary || ""}</p>
    <p class="meta">${sourceText}</p>

    <h3>ATS Resume Score</h3>
    ${report.resumeReview
      ? `<article class="roadmap-phase">
          <h3>${report.resumeReview.atsScore}/100</h3>
          <p class="meta">${report.resumeReview.summary || ""}</p>
        </article>`
      : `<p class="meta">ATS score not available yet.</p>`
    }

    <h3>Current Strengths</h3>
    ${listMarkup(report.strengths, "No strengths detected yet.")}

    <h3>Missing Skills</h3>
    ${listMarkup(report.missingSkills, "No gaps detected.")}

    <h3>Recommendations</h3>
    ${listMarkup(report.recommendations, "No recommendations generated.")}

    <h3>Recommended Learning Paths</h3>
    ${pathsMarkup((report.recommendedPaths || []).length > 0 ? report.recommendedPaths : fallbackPathsForRole(report.targetRole))}

    <h3>Resume Changes Needed</h3>
    ${listMarkup(report.resumeReview?.changesNeeded, "No resume edits suggested yet.")}

    <h3>Keyword Gaps for ATS</h3>
    ${listMarkup(report.resumeReview?.keywordGaps, "No keyword gaps identified yet.")}

    <h3>Suggested Rewrite Bullets</h3>
    ${listMarkup(report.resumeReview?.rewrittenBullets, "No rewritten bullets generated yet.")}
  `
}

async function loadLatest(){
  try{
    const data = await apiGet("/ai/skill-gap/latest")
    renderReport(data.report, "ai")
  }catch(_error){
    renderReport(null)
  }
}

async function analyze(){
  const targetRole = document.getElementById("target-role").value.trim()
  const providedSkillsText = document.getElementById("provided-skills").value.trim()
  const resumeText = resumeTextEl.value.trim()
  const jobDescription = document.getElementById("job-description").value.trim()

  if(!targetRole){
    setStatus("Target role is required.", true)
    return
  }
  if(!resumeText && !providedSkillsText){
    setStatus("Provide resume text or skills list.", true)
    return
  }

  try{
    setBusy(true)
    setStatus("")
    const data = await apiPost("/ai/skill-gap/analyze", {
      targetRole,
      providedSkillsText,
      resumeText,
      jobDescription
    })
    renderReport(data.report, data.source)
    setStatus("Skill gap analysis generated and saved.")
  }catch(error){
    setStatus(error.message, true)
  }finally{
    setBusy(false)
  }
}

async function extractPdfText(file){
  const bytes = await file.arrayBuffer()
  const loadingTask = pdfjsLib.getDocument({ data: bytes })
  const pdf = await loadingTask.promise
  const pages = []

  for(let pageNo = 1; pageNo <= pdf.numPages; pageNo += 1){
    const page = await pdf.getPage(pageNo)
    const content = await page.getTextContent()
    const line = content.items.map(item => item.str || "").join(" ").trim()
    if(line){
      pages.push(line)
    }
  }

  return pages.join("\n\n").trim()
}

async function handleResumePdfChange(){
  const file = resumePdfInput.files?.[0]
  if(!file){
    return
  }

  if(file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")){
    setStatus("Please upload a valid PDF resume.", true)
    return
  }

  try{
    setStatus("Extracting text from PDF...")
    const text = await extractPdfText(file)
    if(!text){
      setStatus("Could not read text from this PDF. Try a text-based PDF.", true)
      return
    }
    resumeTextEl.value = text
    setStatus("Resume PDF loaded into Resume Text.")
  }catch(_error){
    setStatus("Failed to parse PDF. Try another file.", true)
  }
}

analyzeBtn.addEventListener("click", analyze)
resumePdfInput.addEventListener("change", handleResumePdfChange)
loadLatest()
